### ISSUE TITLE
Update to use latest Core Components dependency

### ISSUE THREAD

**Issue by keepthebyte** [adobe/aem-spa-project-archetype#121]
## Feature Request

**Is your feature request related to a problem? Please describe.**
An old version of the Core Components is referenced today, the Archetype should use the latest Core Components - as of writing tis is 2.7.0 

**Describe the solution you'd like**
Update the dependency

https://github.com/adobe/aem-spa-project-archetype/blob/master/src/main/resources/archetype-resources/pom.xml

```
            <dependency>
                <groupId>com.adobe.cq</groupId>
                <artifactId>core.wcm.components.all</artifactId>
                <type>zip</type>
                <version>2.2.2</version>
                <scope>provided</scope>
            </dependency>
```

**Comment by samuelmeuli** [comment]
Related: https://github.com/adobe/aem-spa-project-archetype/issues/73 (Core Components are not being embedded)
