### ISSUE TITLE
Angular Archetype discrepancies with Wknd Events code repo

### ISSUE THREAD

**Issue by emd2013** [adobe/aem-spa-project-archetype#133]
The [angular archetype ](https://github.com/adobe/aem-spa-project-archetype/tree/master/src/test/resources/projects/angular/reference/angular-app)and overall code structure is fundamentally and operationally different from the [Wknd Events repo](https://github.com/Adobe-Marketing-Cloud/aem-guides-wknd-events/tree/angular/chapter-8). 

Examples:
Router: [Wknd](https://github.com/Adobe-Marketing-Cloud/aem-guides-wknd-events/blob/angular/chapter-8/angular-app/src/app/app-routing.module.ts) vs [AEM SPA Archetype](https://github.com/adobe/aem-spa-project-archetype/blob/master/src/main/resources/archetype-resources/angular-app/src/app/app-routing.module.ts)
Page component: [Wknd](https://github.com/Adobe-Marketing-Cloud/aem-guides-wknd-events/blob/angular/chapter-8/angular-app/src/app/components/page/page.component.ts) vs [AEM SPA Archetype](https://github.com/adobe/aem-spa-project-archetype/blob/master/src/main/resources/archetype-resources/angular-app/src/app/components/page/page.component.ts)
App Module: [Wknd](https://github.com/Adobe-Marketing-Cloud/aem-guides-wknd-events/blob/angular/chapter-8/angular-app/src/app/app.module.ts) vs [AEM SPA Archetype](https://github.com/adobe/aem-spa-project-archetype/blob/master/src/main/resources/archetype-resources/angular-app/src/app/app.module.ts)

**Which approach is the more correct way of doing AEM SPA apps?**

**Comment by davidjgonzalez** [comment]
@emd2013  these changes looks largely cosmetic. You should start with w/ SPA Archetype and adjust as needed.

The Router may not appear cosmetic on the surface, however the SPA Editor JS SDK (and archetype) was augmented to abstract some of the boilerplate complexity away... for example, the JS SDK exposes the definition of the `AemPageRouteReuseStrategy` in the WKND tutorial into the SDK provided `AemPageRouteReuseStrategy`  -- same with `AemPageDataResolver`.

**Comment by habansal** [comment]
@emd2013 If your concern has been addressed, I will close this issue. Let us know otherwise.
