### ISSUE TITLE
The desired archetype does not exist (com.adobe.cq.spa.archetype:aem-spa-project-archetype:4.0.0

### ISSUE THREAD

**Issue by emd2013** [adobe/aem-spa-project-archetype#134]
Getting the following error when running the command:

> mvn archetype:generate \
>   -DarchetypeCatalog=remote \
>   -DarchetypeGroupId=com.adobe.cq.spa.archetypes \
>   -DarchetypeArtifactId=aem-spa-project-archetype \
>   -DarchetypeVersion=4.0.0
> 

**The desired archetype does not exist (com.adobe.cq.spa.archetype:aem-spa-project-archetype:4.0.**

**Comment by samuelmeuli** [comment]
I'm afraid I cannot reproduce this. I removed my `settings.xml` file, copy-pasted the command from the README, and it's working for me.

You can see here that the project is available on the Central Repository: https://search.maven.org/artifact/com.adobe.cq.spa.archetypes/aem-spa-project-archetype/4.0.0/maven-archetype

**Comment by emd2013** [comment]
error on my end, please close!
