### ISSUE TITLE
[Angular] Authorable component does not refresh automatically when in AEM Edit mode

### ISSUE THREAD

**Issue by emd2013** [adobe/aem-spa-project-archetype#135]
When creating an angular component and mapped to a corresponding AEM component,[ per the instructions here](https://docs.adobe.com/content/help/en/experience-manager-64/developing/headless/spas/spa-overview.html), when authoring the component in AEM Edit mode, the author has to refresh the page manually to see the authored changes of that component's dialog.

**Comment by habansal** [comment]
@emd2013 Can you provide more details about this issue ?
I can see the changes on the page after editing the component without any page refresh.

Please provide the exact detailed steps to reproduce the issue.

P.S. : Please check if it is the same issue as https://github.com/adobe/aem-spa-project-archetype/issues/18

**Comment by emd2013** [comment]
hey @habansalI the text componet works fine. Issue is with a custom component:

Steps to reproduce:

- Use the archetype to generate a starter kit and upload it on an AEM instance.
- Develop a custom angular/AEM component following the basic guidelines here: https://helpx.adobe.com/experience-manager/kt/sites/using/getting-started-spa-wknd-tutorial-develop/angular/chapter-8.html
- Navigate to any page generated by the archetype
 - Add that custom component
- Open the dialog and edit once
-  save (The issue already occurred)

Current
The custom component isn't properly updated with the expected content

Expected
The custom component is properly updated with the expected content

**Comment by emd2013** [comment]
@habansal following up

**Comment by samuelmeuli** [comment]
@emd2013 It's working for me in the [WKND Events](https://github.com/Adobe-Marketing-Cloud/aem-guides-wknd-events) project (branch `angular/chapter-8`). Is this issue specific to the archetype? If so, would you be able to provide a sample repo?

**Comment by samuelmeuli** [comment]
The SPA archetype has been merged into the [general AEM archetype](https://github.com/adobe/aem-project-archetype). @emd2013, if this problem still occurs, please create a new issue in that repository.
