### ISSUE TITLE
[React] Provide a non-ejected version of the Create React App

### ISSUE THREAD

**Issue by godanny86** [adobe/aem-spa-project-archetype#26]
Ideally, the starter kit should generate a react-app that is not ejected from the Create React App script. This will provide several benefits:

* Simplifies the react-app project configuration and minimizes the dependencies to track
* Starts the project using conventions recommended by Facebook
* Easy for customers to update to the latest version or customize
* Common starting point for React developers

**Comment by lydiapuric** [comment]
Thanks @godanny86! Merged to development. 
Follow-up issue for Jest tests created, see https://github.com/adobe/aem-spa-project-archetype/issues/36
