### ISSUE TITLE
Why have All-in-One module?

### ISSUE THREAD

**Issue by godanny86** [adobe/aem-spa-project-archetype#34]
I understand this will serve a single package to AEM, which will include two sub-packages of ui.apps and core, but is there a significant advantage here? 
It slightly complicates the archetype and differs from https://github.com/Adobe-Marketing-Cloud/aem-project-archetype. The two archetypes should be as closely aligned as possible. When not directly related to SPA capabilities, established conventions of the aem-project-archetype should be used.

**Comment by lydiapuric** [comment]
Thanks @godanny86!
We are aware that there is the aem-project-archetype. We tried to align them as close as possible with restricted initial setup for SPA.
ui.apps defines a restricted set of components page, app and text which proxy the core components. Additionally the page component differs in case you use react or angular as frontend. This is the use case here. The core bundle currently needs to provide the HierarchyPage implementation to be able to extend the SPA required model. We are currently in the process to integrate this extension in the core components so there is no need for a core bundle to be provided.
Lydia :)
Can you please elaborate and clarify your sentence: When not directly related to SPA capabilities, established conventions of the aem-project-archetype should be used.
What do you think we are missing in the archetpye for the dedicated usecase SPA?
Lydia

**Comment by godanny86** [comment]
Hi @lydiapuric! I'm just saying there doesn't appear to be a need for the All-in-one module and that when in doubt the conventions established by the aem-project-archetype should be used. The aem-project-archetype also includes a core module which includes some sample Java code and this is embedded in the ui.apps module. I'm still not seeing the need for the All-in-one module?

**Comment by lydiapuric** [comment]
The main reason for an All-in-one package was to restrict the show case for SPA.
While the aem-project-archetype will contain different modules to be shown as best cases for new AEM projects, the spa archetype restricts the use case for SPA to get a smooth start. The SPA archetype can be integrated into an existing AEM project to start without distraction and to understand what has to be done.
The profile `autoInstallPackage` handles the bundle case and is available in the core bundle. So yes, you are right, there might be something to sync with. Please feel free to open an issue for that.

**Comment by godanny86** [comment]
Ah, ok. I hadn't thought of that use case. I would think that most SPA projects are stand-alone but makes sense I suppose. Will open a separate issue for the bundle. Thanks!

**Comment by lydiapuric** [comment]
Thank you Daniel for your feedback! Resolving this issue.
