### ISSUE TITLE
autoInstallBundle profile missing for Core Module

### ISSUE THREAD

**Issue by godanny86** [adobe/aem-spa-project-archetype#35]
An established AEM convention is to use the profile `autoInstallBundle` to deploy just a project's OSGi bundles to a local AEM instance. Currently, this is done with the profile `autoInstallPackage`. In order to promote consistency across projects the `autoInstallBundle` profile should be used.

**Comment by lydiapuric** [comment]
PR in https://github.com/adobe/aem-spa-project-archetype/pull/45

**Comment by pfauchere** [comment]
Closing as https://github.com/adobe/aem-spa-project-archetype/pull/45 has been released
