### ISSUE TITLE
Remove 'react' optionFrontend param selection from the default

### ISSUE THREAD

**Issue by gutsy** [adobe/aem-spa-project-archetype#39]
Leave off this selection as a default value, so the user has to choose as angular and react are both working options in the AEM SPA editor

**Comment by lydiapuric** [comment]
Agreed and will be addressed: There will be no default value for optionFrontend param provided. 
Note: There is a known issue with required properties to set which have default values, see https://issues.apache.org/jira/browse/ARCHETYPE-308?attachmentSortBy=fileName.

**Comment by lydiapuric** [comment]
Will be addressed with https://github.com/adobe/aem-spa-project-archetype/issues/41
