### ISSUE TITLE
UTF-8 Missing in <head> tag

### ISSUE THREAD

**Issue by pawan-mittal** [adobe/aem-spa-project-archetype#43]
Hi, I have found  `<meta charset="utf-8" />` missing in public/index.html which broke my fonts and were not loaded on page and giving 304.

**Before adding UTF-8**

![screenshot 2019-01-24 at 2 10 43 pm](https://user-images.githubusercontent.com/5343404/51665500-e3b67900-1fe1-11e9-83ef-f7d6a4b2c5f2.png)

**After adding UTF-8**
![screenshot 2019-01-24 at 2 12 16 pm](https://user-images.githubusercontent.com/5343404/51665577-182a3500-1fe2-11e9-8eaa-a9f6000b1e1b.png)

**Comment by lydiapuric** [comment]
PR provided by @pawan-mittal, see https://github.com/adobe/aem-spa-project-archetype/pull/44

**Comment by pawan-mittal** [comment]
Thanks. It's merged in the development branch. :)
