### ISSUE TITLE
Angular/React-built Clientlibs shouldn't us AEM GCC minification

### ISSUE THREAD

**Issue by davidjgonzalez** [adobe/aem-spa-project-archetype#51]
https://github.com/adobe/aem-spa-project-archetype/blob/4ce2eaa02d49cedef6e68a29a5f613360862d9a0/src/main/resources/archetype-resources/angular-app/clientlib.config.js#L28

AEM ships with an old GCC. It doesn't seem wise to run the JS code through AEM's old GCC when, at build time, we have the most modern minification tools at our disposal in the Node ecosystem.

The JS delivered into the clientlib should already be optimized and minified by the webpack build.

**Comment by pfauchere** [comment]
Thx, we will investigate what is the proper configuration. And as you said, it seems like no configuration should be actually set

**Comment by pfauchere** [comment]
The clientlib configuration should probably be something like `jsProcessor: ["default:none", "min:none"]`
