### ISSUE TITLE
[Angular] Installed Angular version is 6; latest version is 7

### ISSUE THREAD

**Issue by davidjgonzalez** [adobe/aem-spa-project-archetype#52]
https://github.com/adobe/aem-spa-project-archetype/blob/4ce2eaa02d49cedef6e68a29a5f613360862d9a0/src/main/resources/archetype-resources/angular-app/package.json#L24

The installed Angular version is 6, which is old. The latest stable version is 7.  

Is there a reason why cannot install the latest stable version of Angular, since we are not allowing the Angular version itself to be selected?

[1] https://www.npmjs.com/package/@angular/core

**Comment by pfauchere** [comment]
No particular reason. We indeed may want to update the version of that dependency. That said, we should probably only target major bumps or security fixes
