### ISSUE TITLE
Naming mismatch between Angular and React

### ISSUE THREAD

**Issue by davidjgonzalez** [adobe/aem-spa-project-archetype#53]
https://github.com/adobe/aem-spa-project-archetype/blob/4ce2eaa02d49cedef6e68a29a5f613360862d9a0/src/main/resources/archetype-resources/angular-app/src/app/components/main-content/main-content.component.ts#L29

It would be good to standardize on naming and idioms used across the SPA projects. 
In Angular this is called "MainContenComponet" and in the React app, its the "PageComponent", yet they represent the same logical construct.

**Comment by pfauchere** [comment]
@davidjgonzalez Once again, I fully agree and also notice the misalignment. We'll consider this fix for the next release
