### ISSUE TITLE
[Angular] Pre-compiled AEM responsive grid included

### ISSUE THREAD

**Issue by davidjgonzalez** [adobe/aem-spa-project-archetype#55]
https://github.com/adobe/aem-spa-project-archetype/blob/4ce2eaa02d49cedef6e68a29a5f613360862d9a0/src/main/resources/archetype-resources/angular-app/src/assets/responsive.css#L17

While removing the AEM dependency for the responsive grid is great, AEM's responsive grid is generated via parameterized inputs (IIRC gutter, and columns?). It appears a  pre-baked grid is included that as generated using opaque params.

It would be better if AEM Responsive Grid can be pulled out into an NPM module that can be included and parameterized to the customer's needs.

**Comment by pfauchere** [comment]
This stylesheet is only used for frontend development. Thus, we differed the creation of such a tool
