### ISSUE TITLE
[Angular] CustomModelClient purpose unclear

### ISSUE THREAD

**Issue by davidjgonzalez** [adobe/aem-spa-project-archetype#58]
https://github.com/adobe/aem-spa-project-archetype/blob/4ce2eaa02d49cedef6e68a29a5f613360862d9a0/src/main/resources/archetype-resources/angular-app/CustomModelClient.js#L27

It appears that the CustomModelClient was accidentally left over (it is floating outside the /app folder). This file is also ~undocumented making it confusing as to its purpose and/or how/when to use it. 

I'd recommend moving sample snippets into documentation, and documenting them well.

See how the angular project tackles exposing sample/illustrative code for ideas: https://angular.io/guide/http#intercepting-requests-and-responses

**Comment by pfauchere** [comment]
The `DEVELOPMENT.md` file [0] contains some vague explanation of when and how to use the `CustomModelClient` class. We recently made some change in the React project where we conditionally use the `CustomModelClient` when starting the development server. We should probably align the `Angular` project accordingly.

[0] https://github.com/adobe/aem-spa-project-archetype/blob/development/src/main/resources/archetype-resources/angular-app/DEVELOPMENT.md

**Comment by pfauchere** [comment]
Could be resolved when working on https://github.com/adobe/aem-spa-project-archetype/issues/74
