### ISSUE TITLE
[React] Support quick syncing to AEM

### ISSUE THREAD

**Issue by ittaibaratz** [adobe/aem-spa-project-archetype#64]
If I want to test my app in AEM, currently I have to run Maven at the top folder which completes in about 2 minutes.

As a Frontend developer, I want to be able to quickly synchronize the app into AEM without having to go through Maven. The workflow is going to be as simple as:

1. "npm run sync" - This will run a listener which will watch the aem folder for changes
2. "npm run build" - In order to build the app. This takes time but still much faster than running Maven.

Pull request coming shortly.

**Comment by godanny86** [comment]
@ittaibaratz while not exactly the same, there is the option of proxying the JSON from AEM and using the webpack dev server...

**Comment by ittaibaratz** [comment]
> @ittaibaratz while not exactly the same, there is the option of proxying the JSON from AEM and using the webpack dev server...

That's what I am doing, however I keep running into areas where the app renders differently inside the aem author and that ends up consuming a lot of my time. I already put a PR to show how this can be done very easily.

**Comment by godanny86** [comment]
understood @ittaibaratz. Curious to know what areas of the app renders differently inside AEM author as that hurts the value prop of the feature and would be good for customers to watch out for.

**Comment by habansal** [comment]
Closing this issue, as it's already fixed and the PR merged
