### ISSUE TITLE
[React] use Router instead of BrowserRouter

### ISSUE THREAD

**Issue by ittaibaratz** [adobe/aem-spa-project-archetype#67]
This is needed in order to allow using the history object to programmatically move between routes.

This is a simple change, and I'll provide a PR when I get to it. It is explained properly [here](https://stackoverflow.com/questions/42701129/how-to-push-to-history-in-react-router-v4).

Essentially we need to change the following in index.js:
`<BrowserRouter>
        <App cqChildren=... />
  </BrowserRouter>), document.getElementById('page'));`

to 
`     const history=createBrowserHistory();
     ...
     <Router history={history}>
        <App history={history} cqChildren=... />
    </Router>
`

This will give <App> access to the history object, allowing it to update routes as a result of state changes.

**Comment by lydiapuric** [comment]
@ittaibaratz Thanks for using the archetype and your effort to report the issues.
Your proposed improvement sounds good. Looking for your contribution.

**Comment by ittaibaratz** [comment]
Thanks @lydiapuric , pull request created.
