### ISSUE TITLE
ui.apps - Wrong vault configuration

### ISSUE THREAD

**Issue by ittaibaratz** [adobe/aem-spa-project-archetype#69]
The /apps/APP folder should not use merge mode. This means that when we update our components, those updates will not reflect when we install a newer package. 

`    <filter root="/apps/mysamplespa" mode="merge"/> `

**Comment by lydiapuric** [comment]
@ittaibaratz Thanks for reporting.
The filter for apps uses merge mode so this archetype does not destroy any custom datain case you have already an project with the same name.
Imagine the use case you start building your spa app and you want to sync at any time with the archetype.

**Comment by godanny86** [comment]
I have to agree with @ittaibaratz, it has long been a standard that `/apps` is overwritten every time as is the case with [0] in the aem project archetype. I'm not sure what you mean by "sync" with the archetype?

[0] - https://github.com/adobe/aem-project-archetype/blob/master/src/main/archetype/ui.apps/src/main/content/META-INF/vault/filter.xml

**Comment by lydiapuric** [comment]
What I mean with sync is if you generate a new version of the archetype to get the latest status and try to update / sync your existing project.
If there is no need and the project archetype handles is different, then let's just adjust the vault filter for /apps. no strong feeling here from my side.

**Comment by pfauchere** [comment]
issue tracked internally by CQ-4266180
