### ISSUE TITLE
.gitignore files are not created automatically

### ISSUE THREAD

**Issue by ittaibaratz** [adobe/aem-spa-project-archetype#71]
The archetype template contains default gitignore files, however they are not copied to the generated project.

The gitignore files should be automatically copied to the project to save developer efforts.

**Comment by pfauchere** [comment]
[0] Could be the beginning of an answer

[0] http://linkedlist.cz/2018/01/10/maven-archetype-gitignore.html

**Comment by ittaibaratz** [comment]
Good find @pfauchere  - Pull request created. I've also added a configuration for maven-resource-plugin to not copy node_modules if it exists
