### ISSUE TITLE
wrong path of filter.xml in pom.xml

### ISSUE THREAD

**Issue by cqsapient** [adobe/aem-spa-project-archetype#84]
In pom.xml of ui.apps and ui.content, the path of filter.xml in

`<filterSource>${basedir}/META-INF/vault/filter.xml</filterSource>`

tag is incorrect 

so the packages deployed in AEM don't have filter.xml and can't be uninstalled.

The correct path is

`<filterSource>${basedir}/src/main/content/META-INF/vault/filter.xml</filterSource>`

This issue is in the latest 1.1.1-SNAPSHOT version from develop branch

**Comment by pfauchere** [comment]
Thank you very much for taking the time to report the issue. Feel free to submit a PR and accelerate the delivery of the fix

**Comment by tsimlin** [comment]
@pfauchere attached you can find a patch within zip. Could not create a PR

[patch.zip](https://github.com/adobe/aem-spa-project-archetype/files/3285938/patch.zip)
